name: mitre-securing-ai
channels:
  - defaults
dependencies:
  - click=7.1.*
  - cloudpickle=1.6.*
  - cython=0.29.*
  - docker-py=4.3.*
  - entrypoints=0.3
  - gitpython=3.1.*
  - gunicorn=20.0.*
  - jinja2=2.11.*
  - nomkl=3.0
  - numpy=1.19.*
  - pandas=1.1.*
  - pip
  - protobuf=3.13.0.1
  - psycopg2=2.8.*
  - python-dateutil=2.8.*
  - python=3.7.*
  - pytz=2020.1
  - pyyaml=5.3.1
  - requests=2.25.0
  - scipy=1.4.1
  - simplejson=3.17.*
  - six=1.13.0
  - sqlalchemy=1.3.13
  - sqlparse=0.4.*
  - werkzeug=1.0.*
  - pip:
      - alembic<=1.4.1
      - boto3>=1.16.0
      - databricks-cli==0.13.0
      - Flask>=1.1.0
      - gorilla==0.3.0
      - mlflow==1.12.1
      - prometheus-flask-exporter==0.18.1
      - querystring-parser>=1.2.0
