# This Software (Dioptra) is being made available as a public service by the
# National Institute of Standards and Technology (NIST), an Agency of the United
# States Department of Commerce. This software was developed in part by employees of
# NIST and in part by NIST contractors. Copyright in portions of this software that
# were developed by NIST contractors has been licensed or assigned to NIST. Pursuant
# to Title 17 United States Code Section 105, works of NIST employees are not
# subject to copyright protection in the United States. However, NIST may hold
# international copyright in software created by its employees and domestic
# copyright (or licensing rights) in portions of software that were assigned or
# licensed to NIST. To the extent that NIST holds copyright in this software, it is
# being made available under the Creative Commons Attribution 4.0 International
# license (CC BY 4.0). The disclaimers of the CC BY 4.0 license apply to all parts
# of the software developed or licensed by NIST.
#
# ACCESS THE FULL CC BY 4.0 LICENSE HERE:
# https://creativecommons.org/licenses/by/4.0/legalcode
include:
  - local: ci/gitlab-ci-build-code.yml
  - local: ci/gitlab-ci-mlflow-tracking.yml
  - local: ci/gitlab-ci-nginx.yml
  - local: ci/gitlab-ci-python-build.yml
  - local: ci/gitlab-ci-pytorch-cpu.yml
  - local: ci/gitlab-ci-pytorch-gpu.yml
  - local: ci/gitlab-ci-restapi.yml
  - local: ci/gitlab-ci-sphinx.yml
  - local: ci/gitlab-ci-tensorflow2-cpu.yml
  - local: ci/gitlab-ci-tensorflow2-gpu.yml
  - local: ci/gitlab-ci-tox-py37.yml
  - local: ci/gitlab-ci-tox-py38.yml
  - local: ci/gitlab-ci-unit-tests.yml
  - local: ci/gitlab-ci-version-vars.yml

variables:
  PROJECT_PREFIX: securing-ai

stages:
  - build:image:ci
  - build:code
  - test:code
  - build:image:lab
  - deploy

pages:
  stage: deploy
  needs:
    - build:docs
  script:
    - mv docs/build public
  tags:
    - sphinx
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "master"'
