# NOTICE
#
# This software (or technical data) was produced for the U. S. Government under
# contract SB-1341-14-CQ-0010, and is subject to the Rights in Data-General Clause
# 52.227-14, Alt. IV (DEC 2007)
#
# © 2021 The MITRE Corporation.
include:
  - local: ci/gitlab-ci-build-code.yml
  - local: ci/gitlab-ci-mlflow-tracking.yml
  - local: ci/gitlab-ci-nginx.yml
  - local: ci/gitlab-ci-python-build.yml
  - local: ci/gitlab-ci-pytorch-cpu.yml
  - local: ci/gitlab-ci-pytorch-gpu.yml
  - local: ci/gitlab-ci-restapi.yml
  - local: ci/gitlab-ci-sphinx.yml
  - local: ci/gitlab-ci-tensorflow2-cpu.yml
  - local: ci/gitlab-ci-tensorflow2-gpu.yml
  - local: ci/gitlab-ci-tox-py37.yml
  - local: ci/gitlab-ci-tox-py38.yml
  - local: ci/gitlab-ci-unit-tests.yml
  - local: ci/gitlab-ci-version-vars.yml

variables:
  PROJECT_PREFIX: securing-ai

stages:
  - build:image:ci
  - build:code
  - test:code
  - build:image:lab
  - deploy

pages:
  stage: deploy
  needs:
    - build:docs
  script:
    - mv docs/build public
  tags:
    - sphinx
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "master"'
