stages:
  - build
  - test
  - deploy

docs-build:
  stage: build
  script:
    - sphinx-build -b html docs/source docs/build
  tags:
    - sphinx
  artifacts:
    paths:
      - docs/build

test-unit-py37:
  image: artifacts.mitre.org:8200/untrusted-mitrewide-overwritable/securing-ai/tox-py37:latest
  stage: test
  script:
    - tox -e clean,pytest
  tags:
    - test-unit
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox

test-unit-py38:
  image: artifacts.mitre.org:8200/untrusted-mitrewide-overwritable/securing-ai/tox-py38:latest
  stage: test
  script:
    - tox -e clean,pytest
  tags:
    - test-unit
  artifacts:
    paths:
      - coverage
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox

test-black:
  image: artifacts.mitre.org:8200/untrusted-mitrewide-overwritable/securing-ai/tox-py38:latest
  stage: test
  script:
    - tox -e black
  tags:
    - test-unit
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox

test-isort:
  image: artifacts.mitre.org:8200/untrusted-mitrewide-overwritable/securing-ai/tox-py38:latest
  stage: test
  script:
    - tox -e isort
  tags:
    - test-unit
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox

test-flake8:
  image: artifacts.mitre.org:8200/untrusted-mitrewide-overwritable/securing-ai/tox-py38:latest
  stage: test
  script:
    - tox -e flake8
  tags:
    - test-unit
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox

test-mypy:
  image: artifacts.mitre.org:8200/untrusted-mitrewide-overwritable/securing-ai/tox-py38:latest
  stage: test
  script:
    - tox -e mypy
  tags:
    - test-unit
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox

test-gitlint:
  image: artifacts.mitre.org:8200/untrusted-mitrewide-overwritable/securing-ai/tox-py38:latest
  stage: test
  script:
    - tox -e gitlint
  tags:
    - test-unit
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox

pages:
  stage: deploy
  needs:
    - docs-build
  script:
    - mv docs/build public
  tags:
    - sphinx
  artifacts:
    paths:
      - public
  only:
    - master
