name: securing-ai-lab-components
channels:
  - defaults
dependencies:
  - autopep8
  - beautifulsoup4
  - black
  - blinker
  - bottleneck
  - click
  - cloudpickle
  - coverage
  - cython
  - dask
  - docker-py
  - entrypoints
  - flake8
  - gitpython
  - gunicorn
  - h5py
  - ipython
  - isort
  - jinja2
  - joblib
  - jupyter
  - markupsafe
  - matplotlib
  - mypy
  - nose
  - numexpr
  - numpy
  - pandas
  - passlib
  - pillow
  - pip
  - protobuf
  - psutil
  - psycopg2
  - pycodestyle
  - pydocstyle
  - pymysql
  - pyodbc
  - pytables
  - python-dateutil
  - python=3.8
  - pytz
  - pyyaml=5.3.0
  - pyzmq
  - redis-py
  - requests
  - scipy=1.4.1
  - setuptools
  - setuptools-scm
  - simplejson
  - six
  - sphinx
  - twine
  - werkzeug
  - wheel
  - pip:
      - -e .
      - adversarial-robustness-toolbox
      - alembic==1.4.1
      - boto3
      - commitizen
      - databricks-cli
      - docformatter
      - Flask
      - flask-accepts
      - Flask-Injector
      - Flask-JWT-Extended
      - Flask-Migrate
      - flask-restx
      - Flask-SQLAlchemy
      - Flask-WTF
      - flake8-bugbear
      - freezegun
      - ghp-import
      - gorilla
      - markdown
      - marshmallow
      - mlflow
      - mnist
      - plantuml-markdown
      - pre-commit
      - prefect
      - prometheus-flask-exporter
      - pyarrow
      - pymdown-extensions
      - pytest
      - pytest-cov
      - pytest-datadir
      - python-json-logger
      - querystring-parser
      - recommonmark
      - rich
      - rq
      - rstcheck
      - scikit-learn==0.22.2
      - seed-isort-config
      - sphinx-rtd-theme
      - sphinx-autobuild
      - sphinx-autodoc-typehints
      - sphinx-book-theme
      - sqlalchemy==1.3.13
      - sqlparse
      - structlog
      - tabulate
      - testinfra
      - tox
      - tox-conda
      - typing-extensions
