name: securing-ai-lab-components
channels:
  - defaults
  - conda-forge
dependencies:
  - alembic
  - autopep8
  - beautifulsoup4
  - black
  - blinker
  - bottleneck
  - click
  - cloudpickle
  - coverage
  - cython
  - docker-py
  - entrypoints
  - flake8
  - flake8-bugbear
  - gitpython
  - gunicorn
  - h5py
  - ipython
  - isort
  - jinja2
  - joblib
  - jupyter
  - markupsafe
  - matplotlib
  - mypy
  - nose
  - numexpr
  - numpy
  - pandas
  - pillow
  - pip=20.0.2
  - pre-commit
  - protobuf
  - psycopg2
  - pycodestyle
  - pydocstyle
  - pymysql
  - pyodbc
  - pytables
  - pytest
  - pytest-cov
  - pytest-datadir
  - python-dateutil
  - python=3.7.7
  - pytz
  - pyyaml=5.3.0
  - pyzmq
  - redis-py
  - requests
  - scikit-learn=0.22.1
  - scipy
  - setuptools=46.1.3
  - setuptools-scm=3.5.0
  - simplejson
  - six
  - testinfra
  - tox
  - tox-conda
  - twine
  - werkzeug
  - wheel=0.34.2
  - pip:
      - -e .
      - adversarial-robustness-toolbox
      - boto3
      - commitizen
      - databricks-cli
      - docformatter
      - Flask
      - flask-accepts
      - Flask-Injector
      - flask-restx
      - ghp-import
      - gorilla
      - markdown
      - marshmallow
      - md-tooltips
      - mdx_include
      - mkdocs
      - mkdocs-build-plantuml-plugin
      - mkdocs-git-revision-date-localized-plugin
      - mkdocs-material
      - mkdocs-minify-plugin
      - mlflow
      - mnist
      - plantuml-markdown
      - prometheus-flask-exporter
      - pyarrow
      - pymdown-extensions
      - python-json-logger
      - querystring-parser
      - recommonmark
      - rich
      - rq
      - seed-isort-config
      - sqlalchemy
      - sqlparse
      - structlog
      - tabulate
      - typing-extensions
