name: securing-ai-lab-components
channels:
  - defaults
dependencies:
  - autopep8
  - beautifulsoup4
  - black
  - blinker
  - bottleneck
  - click
  - cloudpickle
  - coverage
  - cython
  - dask
  - docker-py
  - docopt=0.6.*
  - docutils=0.16
  - entrypoints
  - flake8>=3.8.0
  - gitpython
  - gunicorn
  - h5py
  - ipython
  - isort>=5.6.0
  - jinja2
  - joblib
  - jupyter
  - markupsafe
  - matplotlib
  - mypy
  - networkx=2.4
  - nose
  - numexpr
  - numpy
  - pandas
  - parso>=0.8.0
  - passlib
  - pillow
  - pip
  - protobuf
  - psutil
  - psycopg2
  - pycodestyle
  - pydocstyle
  - pymongo=3.11.*
  - pymysql
  - pyodbc
  - pytables
  - python-dateutil
  - python-jsonrpc-server=0.3.*
  - python=3.8
  - pytz
  - pyyaml=5.3.*
  - pyzmq
  - redis-py
  - requests=2.24.*
  - scipy=1.4.1
  - setuptools
  - simplejson
  - six
  - sphinx
  - toml=0.10.*
  - twine
  - ujson=1.35
  - watchdog=0.10.*
  - werkzeug
  - wheel
  - pip:
      - adversarial-robustness-toolbox
      - alembic==1.4.1
      - black>=20.8b1
      - black[d]
      - boto3
      - build
      - commitizen
      - databricks-cli
      - docformatter
      - fett~=0.3.2
      - flake8-bugbear
      - Flask
      - flask-accepts
      - Flask-Injector
      - Flask-JWT-Extended
      - Flask-Migrate
      - flask-restx
      - Flask-SQLAlchemy
      - Flask-WTF
      - freezegun
      - gorilla
      - markdown
      - marshmallow
      - mlflow
      - mnist
      - plantuml-markdown
      - pre-commit
      - prefect
      - prometheus-flask-exporter
      - pyarrow
      - pymdown-extensions
      - pytest-cov
      - pytest-datadir
      - pytest-testinfra
      - pytest>=5.*,<6
      - python-json-logger
      - querystring-parser
      - recommonmark
      - rich
      - rq
      - rstcheck
      - scikit-learn==0.22.2
      - seed-isort-config
      - snooty
      - sphinx-autobuild
      - sphinx-autodoc-typehints
      - sphinx-book-theme
      - sphinx-copybutton
      - sphinx-rtd-theme
      - sqlalchemy-stubs
      - sqlalchemy==1.3.13
      - sqlparse
      - structlog
      - tabulate
      - tox
      - typing-extensions~=3.7.4.1
