[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.0"
changelog_file = "CHANGELOG.md"
changelog_incremental = true
changelog_start_rev = "v0.0.0"
version_files = [
    "src/mitre/securingai/mlflow_plugins/__version__.py",
    "src/mitre/securingai/pyplugs/__version__.py",
    "src/mitre/securingai/restapi/__version__.py",
    "src/mitre/securingai/rq/__version__.py",
    "docs/source/conf.py:release",
    "Makefile:PROJECT_VERSION",
    "pyproject.toml:version",
    "setup.cfg:version",
]
style = [
    ["qmark", "fg:#ff9d00 bold"],
    ["question", "bold"],
    ["answer", "fg:#ff9d00 bold"],
    ["pointer", "fg:#ff9d00 bold"],
    ["highlighted", "fg:#ff9d00 bold"],
    ["selected", "fg:#cc5454"],
    ["separator", "fg:#cc5454"],
    ["instruction", ""],
    ["text", ""],
    ["disabled", "fg:#858585 italic"],
]
tag_format = "v$major.$minor.$patch"
bump_message = "release $current_version → $new_version"

[tool.isort]
profile = "black"
