# NOTICE
#
# This software (or technical data) was produced for the U. S. Government under
# contract SB-1341-14-CQ-0010, and is subject to the Rights in Data-General Clause
# 52.227-14, Alt. IV (DEC 2007)
#
# © 2021 The MITRE Corporation.
web-compile:
  sass:
    files:
      docs/assets/scss/securing-ai-testbed.scss: docs/source/_static/securing-ai-testbed.css
    precision: 5
    sourcemap: false
    format: compressed
