# NOTICE
#
# This software (or technical data) was produced for the U. S. Government under
# contract SB-1341-14-CQ-0010, and is subject to the Rights in Data-General Clause
# 52.227-14, Alt. IV (DEC 2007)
#
# © 2021 The MITRE Corporation.
name: patch-defended-pixel-threshold
channels:
  - defaults
  - conda-forge
dependencies:
  - autopep8
  - black
  - bottleneck
  - click
  - cloudpickle
  - cython
  - flake8
  - flake8-bugbear
  - h5py
  - ipython
  - isort
  - jinja2
  - joblib
  - jupyter
  - markupsafe
  - matplotlib
  - mypy
  - numexpr
  - numpy
  - pandas
  - pillow
  - pip=20.0.2
  - protobuf
  - pycodestyle
  - pydocstyle
  - pytables
  - python=3.7.7
  - pytz
  - pyyaml=5.3.0
  - requests
  - scikit-learn=0.22.1
  - scipy
  - setuptools=46.1.3
  - setuptools-scm=3.5.0
  - wheel=0.34.2
  - pip:
      - adversarial-robustness-toolbox
      - boto3
      - databricks-cli
      - docformatter
      - Flask
      - gorilla
      - markdown
      - mlflow
      - mnist
      - prometheus-flask-exporter
      - pyarrow
      - python-json-logger
      - rich
      - structlog
      - tabulate
      - tensorflow==2.1.0
      - typing-extensions
