name: tensorflow-mnist-classifier

entry_points:
train:
  model:
    name: CustomModel
    file: vgg16
    class: CustomVGG16Model
    args:
      nodes_per_layer: 16

fgm:
  attack_parameters:
    eps: { type: float, default: 0.3 }
    eps_step: { type: float, default: 0.1 }
    minimal: { type: float, default: 0 }
    norm: { type: string, default: "inf" }
  dataset_parameters:
    batch_size: { type: float, default: 32 }
  common_parameters:
    seed: { type: float, default: -1 }
  dataset_name: mnist
  entrypoint_type: attack
  subtype: evasion
  load_data:
    format: image
    method: tensorflow
    preprocessing:
      - resize
  attack:
    name: FastGradientMethod
    prehook: random_noise_parameters
    posthook: smoothing_defense
    metrics:
      - norm-2
      - norm-1
      - manhattan
  architecture: LeNet-5
  model_registered_name: mnist_le_net/1
  library: tensorflow

infer:
  parameters:
    run_id: { type: string }
    model: { type: string, default: "mnist_le_net/1" }
    model_architecture: { type: string, default: "le_net" }
    batch_size: { type: float, default: 32 }
    seed: { type: float, default: -1 }
  entrypoint_type: infer
  subtype: defended
  defense:
    name: FeatureSqueezing
    prehook: smoothing_defense
  load_data:
    format: numpy
  predict:
    metrics:
      - accuracy
      - roc_auc
      - precision
    prehooks:
      - name: load_second_image
        args:
          format: numpy
          source: previous_run
          artifact: patch.npx
          run_id: 7823987007
      - name: merge_images_random
        args:
          image_center: 0
          keep_original: true
      - name: merge_images
        args:
          image_center: 0
          keep_original: true
          location:
            x: 0.5
            y: 0.5
      - name: save_image
        args:
          image_center: 0
          keep_original: true
