# This Software (Dioptra) is being made available as a public service by the
# National Institute of Standards and Technology (NIST), an Agency of the United
# States Department of Commerce. This software was developed in part by employees of
# NIST and in part by NIST contractors. Copyright in portions of this software that
# were developed by NIST contractors has been licensed or assigned to NIST. Pursuant
# to Title 17 United States Code Section 105, works of NIST employees are not
# subject to copyright protection in the United States. However, NIST may hold
# international copyright in software created by its employees and domestic
# copyright (or licensing rights) in portions of software that were assigned or
# licensed to NIST. To the extent that NIST holds copyright in this software, it is
# being made available under the Creative Commons Attribution 4.0 International
# license (CC BY 4.0). The disclaimers of the CC BY 4.0 license apply to all parts
# of the software developed or licensed by NIST.
#
# ACCESS THE FULL CC BY 4.0 LICENSE HERE:
# https://creativecommons.org/licenses/by/4.0/legalcode
test:unit:py37:
  stage: test:code
  dependencies: []
  script:
    - tox -e clean,pytest
  tags:
    - tox-py37
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_COMMIT_BRANCH"

test:unit:py38:
  stage: test:code
  dependencies: []
  script:
    - tox -e clean,pytest
  tags:
    - tox-py38
  artifacts:
    paths:
      - coverage
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_COMMIT_BRANCH"

test:black:
  stage: test:code
  dependencies: []
  script:
    - tox -e black
  tags:
    - tox-py38
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_COMMIT_BRANCH"

test:isort:
  stage: test:code
  dependencies: []
  script:
    - tox -e isort
  tags:
    - tox-py38
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_COMMIT_BRANCH"

test:flake8:
  stage: test:code
  dependencies: []
  script:
    - tox -e flake8
  tags:
    - tox-py38
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_COMMIT_BRANCH"

test:mypy:
  stage: test:code
  dependencies: []
  script:
    - tox -e mypy
  tags:
    - tox-py38
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_COMMIT_BRANCH"

test:gitlint:
  stage: test:code
  dependencies: []
  script:
    - tox -e gitlint
  tags:
    - tox-py38
  cache:
    key: ${CI_JOB_NAME}--${CI_COMMIT_REF_SLUG}
    paths:
      - .tox
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_COMMIT_BRANCH"
