# NOTICE
#
# This software (or technical data) was produced for the U. S. Government under
# contract SB-1341-14-CQ-0010, and is subject to the Rights in Data-General Clause
# 52.227-14, Alt. IV (DEC 2007)
#
# © 2021 The MITRE Corporation.
build:code:
  stage: build:code
  script:
    - /usr/local/bin/python -m build -sw
  tags:
    - python-build
  artifacts:
    paths:
      - dist
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: "$CI_COMMIT_TAG"
    - if: "$CI_COMMIT_BRANCH"

build:docs:
  stage: build:code
  script:
    - sphinx-build -b html docs/source docs/build
  tags:
    - sphinx
  artifacts:
    paths:
      - docs/build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: "$CI_COMMIT_BRANCH"
