
version: "3.7"

networks:
  username:

services:
  minio-username:
    image: minio/minio:RELEASE.2020-07-12T19-14-17Z
    init: true
    restart: always
    hostname: minio-username
    container_name: minio-username
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    networks:
      - username
    volumes:
      - type: bind
        source: ./s3
        target: /data

  mlflow-tracking-username:
    image: securing-ai/mlflow-tracking:0.0.0-1
    init: true
    restart: always
    hostname: mlflow-tracking-username
    container_name: mlflow-tracking-username
    depends_on:
      - minio-username
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - target: 5000
        published: 35000
        protocol: tcp
        mode: host
    command:
      - --host
      - "0.0.0.0"
      - --default-artifact-root
      - "s3://mlflow-tracking/artifacts"
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      MLFLOW_S3_ENDPOINT_URL: http://minio-username:9000
    networks:
      - username
    volumes:
      - type: bind
        source: ./mlruns
        target: /work/mlruns

  tfcpu-username:
    image: securing-ai/tensorflow2-cpu-py37:0.0.0-1
    init: true
    restart: "no"
    hostname: tfcpu
    container_name: tfcpu
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      MLFLOW_EXPERIMENT_NAME: mnist
      MLFLOW_TRACKING_URI: http://mlflow-tracking-username:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio-username:9000
      KMP_AFFINITY: "none"
      KMP_BLOCKTIME: "1"
      OMP_NUM_THREADS: "6"
      KMP_SETTINGS: "FALSE"
      TF_CPP_MIN_LOG_LEVEL: "2"
      USE_DAAL4PY_SKLEARN: "YES"
    networks:
      - username
    volumes:
      - type: bind
        source: ./data
        target: /nfs/data
