name: tensorflow-mnist-classifier
channels:
  - defaults
  - conda-forge
dependencies:
  - autopep8
  - bottleneck
  - click
  - cloudpickle
  - cython
  - flake8>=3.8.0
  - flake8-bugbear
  - h5py
  - ipywidgets
  - ipython
  - isort>=5.6.0
  - jinja2
  - joblib
  - jupyter
  - jupyterlab
  - jupyterlab_code_formatter
  - markupsafe
  - matplotlib
  - mypy
  - nodejs
  - nomkl
  - numexpr
  - numpy
  - pandas
  - pillow
  - pip
  - protobuf
  - pycodestyle
  - pydocstyle
  - redis-py
  - pytables
  - python=3.7
  - pytz
  - pyyaml=5.3.*
  - requests=2.24.*
  - scipy=1.4.1
  - setuptools
  - wheel
  - pip:
      - adversarial-robustness-toolbox
      - alembic==1.4.1
      - black>=20.8b1
      - boto3
      - databricks-cli
      - docformatter
      - Flask
      - flask-accepts
      - Flask-Injector
      - Flask-JWT-Extended
      - Flask-Migrate
      - flask-restx
      - Flask-SQLAlchemy
      - Flask-WTF
      - gorilla
      - markdown
      - mlflow
      - mnist
      - passlib
      - prometheus-flask-exporter
      - pyarrow
      - python-json-logger
      - rich
      - rq
      - scikit-learn==0.22.2
      - sqlalchemy-stubs
      - sqlalchemy==1.3.13
      - structlog
      - tabulate
      - tensorflow==2.1.0
      - typing-extensions~=3.7.4.1
